#!/usr/bin/python

#Definine class for node having value and address for next node
class node:
    def __init__(self, val):
        self.value = val
        self.next = None

class list:
    def __init__(self, head = None):
        self.head = head

    def insert(self, val):
        if not self.head:
            self.head = node(val)
        else:
            temp = self.head
            while temp.next:
                temp = temp.next
            temp.next = node(val)

    def showlist(self):
        if not self.head:
            print "List is empty"
        else:
            temp = self.head
            print temp.value,
            while temp.next:
                temp = temp.next
                print "-->%d" % temp.value,



if __name__ == "__main__":
    l = list(node(8))
    l.insert(5)
    l.insert(10)
    l.showlist()
        
