#!/usr/bin/python
class Solution(object):
    def moveZeroes(self, nums):
        """
        :type nums: List[int]
        :rtype: void Do not return anything, modify nums in-place instead.
        """
        swap = 0
        for i in range(len(nums)):
            if(nums[i] != 0):
                temp = nums[i]
                nums[i] = 0
                nums[swap] = temp    
                swap += 1
