#!/usr/bin/python
import sys
def t(s):
    record = [0]*256

    for i in s[0:]:
        if(record[ord(i)] != 0):
           return False
        else:
           record[ord(i)] = 1
    return True



if __name__ == "__main__":
   print t(sys.argv[1])
